# Generated by Django 2.2 on 2019-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_pagedetail_parentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sirketadi', models.CharField(max_length=150)),
                ('adres', models.CharField(max_length=150)),
                ('telefon', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=150)),
                ('sosyalmedya', models.CharField(max_length=150)),
                ('hakkimizdakisa', models.CharField(max_length=150)),
                ('haberbir', models.CharField(max_length=150)),
                ('haberesimbir', models.ImageField(upload_to='images/')),
                ('tarihbir', models.CharField(max_length=150)),
                ('haberiki', models.CharField(max_length=150)),
                ('tarihiki', models.CharField(max_length=150)),
                ('haberresimiki', models.ImageField(upload_to='images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kampanya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('baslikbir', models.CharField(max_length=150)),
                ('baslikiki', models.CharField(max_length=150)),
                ('yazibir', models.CharField(max_length=150)),
                ('yaziiki', models.CharField(max_length=150)),
                ('yaziuc', models.CharField(max_length=150)),
                ('yazidort', models.CharField(max_length=150)),
                ('indirim', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
